apiVersion: v1
kind: Service
metadata:
  labels:
    app: ddcc-gateway-postgres
  name: ddcc-gateway-postgres
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
